my:
  ip: localhost
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengqian117/learn
          search-paths: config-repo
          default-label: master
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    port: 5672
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://${my.ip}:8761/eureka,http://${my.ip}:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"

