spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka


