my:
  ip: localhost
eureka:
  client:
    service-url:
      defaultZone: http://${my.ip}:8761/eureka,http://${my.ip}:8762/eureka
spring:
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    port: 5672
