spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengqian117/learn
          search-paths: config-repo
          default-label: master
  profiles:
    active: prod
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "*"

