ttt: hello word! 你好啊!

logging:
  config: classpath:logback.xml
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  jackson:
    time-zone: GMT+8

  datasource:
    #url: jdbc:oracle:thin:@192.168.0.1:1521:a
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456asd
    #214环境
    #url: jdbc:mysql://127.0.0.1:3306/datauser
    #username: root
    #password: root
    #    url: jdbc:oracle:thin:@//192.168.1.5:1521/orcl
    #    username:
    #    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: "config.decrypt=true;config.decrypt.key=dfdffdg"
    druid:
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，‘wall'用于防火墙
      #filters: stat,wall,log4j
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 5
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性打开mergeSql功能；慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 5
      timeBetweenEvictionRunsMills: 60000
      minEvictabledleTimeMills: 3000000
      validationQuery: select 1 from dual
      testWhileldle: true
      testOnBorrow: false
      testOnRetrun: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.softi.subwayMap.modules
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


pagehelper:
  helperDialect: mysql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
managment:
  security:
    enabled: false